# Generated by Django 5.2.3 on 2025-08-21 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='PhotoManager',
        ),
    ]
